// The seeded book of cases, ported verbatim from the "01 Cockpit" design prototype.
// Em dashes in the original copy are normalized to the repo writing rule (commas,
// semicolons or "->"). This is the starting state written to localStorage on first load.

import type { Case } from "@/lib/cockpit-types";

export function seedCases(): Case[] {
  return [
    {
      id: "helvetia",
      owner: "rm",
      client: "Helvetia Capital AG",
      lei: "5493 00HEL VETIA 1A2",
      domicile: "Zug, CH",
      sector: "Asset Management",
      band: "HIGH",
      prevBand: "MEDIUM",
      status: "flagged_by_rm",
      decision: null,
      instructionDone: false,
      unread: true,
      materiality: 92,
      headline:
        "Stated business model shifted from B2B SaaS to crypto OTC brokerage, alongside a new >10% shareholder.",
      signals: [
        { label: "Business model change · SaaS -> crypto OTC", pts: 34 },
        { label: "New >10% beneficial owner · BVI nominee", pts: 28 },
        { label: "Jurisdiction risk · BVI layer", pts: 18 },
        { label: "Prior band already MEDIUM", pts: 12 },
      ],
      changes: [
        {
          dir: "negative",
          text: "Business model changed from B2B SaaS to crypto OTC brokerage",
          src: "Company filing · 18 Jun",
        },
        {
          dir: "negative",
          text: "New shareholder Triton Ventures Ltd (BVI) acquired a 14% stake",
          src: "Commercial register · 17 Jun",
        },
        { dir: "neutral", text: "Registered office unchanged (Zug)", src: "System" },
      ],
      facts: ["AUM CHF 480M", "Onboarded 2021", "Last KYC review Mar 2024", "No PEP on file"],
      recAction: "escalate_compliance",
      recLabel: "Escalate to Compliance for Re-KYC",
      recRationale:
        "Material business-model change plus a new beneficial owner crosses the re-KYC threshold; this belongs with the second line.",
      compRec: "re_kyc",
      messages: [
        {
          from: "rm",
          to: "compliance",
          text: "New shareholder + crypto pivot, looks material, sending up for review.",
          ts: "20 Jun 07:03",
        },
      ],
      audit: [
        {
          ts: "19 Jun 06:12",
          actor: "System",
          action: "Detected business-model drift (SaaS -> crypto OTC)",
        },
        {
          ts: "20 Jun 07:03",
          actor: "Lena Brunner · RM",
          action: "Escalated to Compliance (1st -> 2nd line)",
        },
      ],
    },

    {
      id: "bernina",
      owner: "rm",
      client: "Bernina Wealth Partners",
      lei: "5493 00BER NIN 4K5",
      domicile: "St. Moritz, CH",
      sector: "Private Wealth",
      band: "MEDIUM",
      prevBand: "LOW",
      status: "open",
      decision: null,
      instructionDone: false,
      unread: false,
      materiality: 58,
      headline:
        "The relationship has grown structurally complex; a new discretionary mandate, two trust layers and an offshore feeder now sit under one client.",
      signals: [
        { label: "New discretionary mandate + 2 trust structures", pts: 30 },
        { label: "Offshore feeder fund added", pts: 18 },
        { label: "Servicing complexity beyond RM remit", pts: 14 },
      ],
      changes: [
        {
          dir: "negative",
          text: "Two new trust structures (JE, LI) inserted above the account",
          src: "Onboarding pack · 16 Jun",
        },
        {
          dir: "negative",
          text: "Offshore feeder fund (KY) added to the mandate",
          src: "Mandate doc · 16 Jun",
        },
        {
          dir: "neutral",
          text: "No adverse media; no ownership-control change",
          src: "System",
        },
      ],
      facts: ["AUM CHF 220M", "Onboarded 2019", "Last KYC review Sep 2024", "No PEP on file"],
      recAction: "handover_am",
      recLabel: "Hand over to the Account Manager",
      recRationale:
        "This is complexity, not a red flag. The client now needs structural servicing the RM does not own; reassign within the first line to the Account Manager rather than escalating to Compliance.",
      compRec: "doc_request",
      messages: [],
      audit: [
        {
          ts: "16 Jun 08:40",
          actor: "System",
          action: "Detected structural complexity increase",
        },
      ],
    },

    {
      id: "castor",
      owner: "rm",
      client: "Castor Mining Ltd",
      lei: "5493 00CAS TOR 9Z8",
      domicile: "Lugano, CH",
      sector: "Commodities",
      band: "HIGH",
      prevBand: "MEDIUM",
      status: "open",
      decision: null,
      instructionDone: false,
      unread: false,
      materiality: 78,
      headline: "A director was named in an investigative report on a sanctions-evasion network.",
      signals: [
        { label: "Adverse media · director sanctions probe", pts: 40 },
        { label: "High-risk sector · commodities", pts: 20 },
        { label: "Counterparty on flagged shipments", pts: 18 },
      ],
      changes: [
        {
          dir: "negative",
          text: "Director A. Volkov named in OCCRP report on a sanctions-evasion network",
          src: "Adverse media · 19 Jun",
        },
        {
          dir: "negative",
          text: "Counterparty on two flagged commodity shipments",
          src: "Trade data · 19 Jun",
        },
      ],
      facts: ["Revenue est. CHF 210M", "Onboarded 2019", "Last KYC review Nov 2023", "High-risk sector"],
      recAction: "escalate_compliance",
      recLabel: "Escalate to Compliance · adverse media",
      recRationale:
        "Credible adverse media on a director is a control matter; escalate to the second line for a watchlist decision.",
      compRec: "watchlist",
      messages: [],
      audit: [
        { ts: "19 Jun 22:40", actor: "System", action: "Adverse-media hit on director" },
      ],
    },

    {
      id: "nordwind",
      owner: "am",
      client: "Nordwind Trading GmbH",
      lei: "5493 00NOR DWI 3C4",
      domicile: "Vaduz, LI",
      sector: "Trading",
      band: "MEDIUM",
      prevBand: "LOW",
      status: "open",
      decision: null,
      instructionDone: false,
      unread: false,
      amUnread: false,
      materiality: 64,
      headline:
        "Ownership is now routed through a new Cyprus holding layer, obscuring the ultimate beneficial owner.",
      signals: [
        { label: "New Cyprus holding layer · UBO obscured", pts: 34 },
        { label: "Ownership opacity increased", pts: 18 },
        { label: "Cross-jurisdiction structure", pts: 12 },
      ],
      changes: [
        {
          dir: "negative",
          text: "Ownership routed through Aether Holdings (CY); UBO obscured",
          src: "Register · 16 Jun",
        },
        { dir: "neutral", text: "Trading volume flat quarter-on-quarter", src: "System" },
      ],
      facts: ["Onboarded 2020", "Last KYC review Jun 2024", "Complex structure", "No PEP on file"],
      recAction: "escalate_compliance",
      recLabel: "Escalate to Compliance · UBO opacity",
      recRationale:
        "Ownership opacity has increased on an account you own; escalate to the second line for a documentation request.",
      compRec: "doc_request",
      messages: [],
      audit: [{ ts: "16 Jun 09:10", actor: "System", action: "Detected new holding layer" }],
    },

    {
      id: "lago",
      owner: "am",
      client: "Lago Holdings SA",
      lei: "5493 00LAG O56 7E8",
      domicile: "Geneva, CH",
      sector: "Holding",
      band: "MEDIUM",
      prevBand: "LOW",
      status: "open",
      decision: null,
      instructionDone: false,
      unread: false,
      amUnread: false,
      materiality: 55,
      headline: "Intercompany guarantees now form a circular exposure loop with two other clients.",
      signals: [
        { label: "Circular intercompany guarantee loop", pts: 30 },
        { label: "Concentration risk across 3 linked entities", pts: 16 },
        { label: "Exposure not previously modelled", pts: 9 },
      ],
      changes: [
        {
          dir: "negative",
          text: "Intercompany guarantees create a circular exposure loop",
          src: "Exposure graph · 18 Jun",
        },
      ],
      facts: ["Onboarded 2018", "Last KYC review Feb 2024", "3 linked entities", "No PEP on file"],
      recAction: "escalate_compliance",
      recLabel: "Escalate to Compliance · circular exposure",
      recRationale: "Circular exposure can mask concentration risk; escalate to the second line.",
      compRec: "watchlist",
      messages: [],
      audit: [{ ts: "18 Jun 11:00", actor: "System", action: "Detected circular exposure" }],
    },

    {
      id: "alpenrose",
      owner: "rm",
      client: "Alpenrose Family Office",
      lei: "5493 00ALP ROS 1Q2",
      domicile: "Zürich, CH",
      sector: "Family Office",
      band: "LOW",
      prevBand: "LOW",
      status: "open",
      decision: null,
      instructionDone: false,
      unread: false,
      quiet: true,
      materiality: 8,
      headline: "No material change overnight.",
      signals: [{ label: "Routine portfolio rebalancing", pts: 5 }],
      changes: [{ dir: "neutral", text: "Routine portfolio rebalancing only", src: "System" }],
      facts: ["AUM CHF 1.2B", "Onboarded 2017", "Last KYC review Jan 2025", "No PEP on file"],
      recAction: "monitor",
      recLabel: "No action, keep monitoring",
      recRationale: "Nothing crossed a threshold overnight.",
      compRec: null,
      messages: [],
      audit: [],
    },

    {
      id: "meridian",
      owner: "rm",
      client: "Meridian Logistics SA",
      lei: "5493 00MER IDI 8R9",
      domicile: "Basel, CH",
      sector: "Logistics",
      band: "LOW",
      prevBand: "LOW",
      status: "open",
      decision: null,
      instructionDone: false,
      unread: false,
      quiet: true,
      materiality: 5,
      headline: "No material change overnight.",
      signals: [{ label: "No news matched · filings current", pts: 3 }],
      changes: [{ dir: "neutral", text: "No news matched. Filings current.", src: "System" }],
      facts: ["Onboarded 2022", "Last KYC review Aug 2024", "Simple structure", "No PEP on file"],
      recAction: "monitor",
      recLabel: "No action, keep monitoring",
      recRationale: "Nothing crossed a threshold overnight.",
      compRec: null,
      messages: [],
      audit: [],
    },
  ];
}
